### PR TITLE
Hi Tony - looks like the build was failing because of an outdated build setting (you probably still have the old path on your Mac?)

### PR DESCRIPTION
**Pull request by danielpunkass**

### CODE REVIEW

**Comment by tonyarnold** [comment]
Yeah, I'm not surprised! Thanks for the PRs. I can't remember what the state of this branch is — I got distracted by work and haven't made more time for this since then.

**Comment by danielpunkass** [comment]
Cool, well I just assumed it has the hotness since it's called "modernize" :)

**Comment by danielpunkass** [comment]
BTW if it is in fact where you have done the most work, consider changing it so the default branch is "modernize" (then the README/etc will show up).

**Comment by tonyarnold** [comment]
It is the hotness, but it may well be completely busted :S 

I'll update the default branch and dive back in tomorrow night. I'd really like to see this app working well again.

**Pull request merged**
